# version: '3.7'

services:
  nginx:
    build: requirements/nginx/
    image: nginx:ouaarabe
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  wordpress:
    build: requirements/wordpress/
    image: wp:ouaarabe
    container_name: wp
    expose:
      - "9000"
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  mariadb:
    build: requirements/mariadb/
    image: mariadb:ouaarabe
    container_name: mariadb
    #expose when the communication is within the network map when wanted access from hosting machine
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart : on-failure
  redis:
    build: requirements/bonus/redis/
    image: redis:ouaarabe
    container_name: redis
    depends_on:
      - wordpress
    expose:
      - "6379"
    networks:
      - inception
    restart: on-failure
  adminer:
    build: requirements/bonus/adminer/
    image: adminer:ouaarabe
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "80:80"
    networks:
      - inception
    restart: on-failure
  static_web:
    build: requirements/bonus/static_web/
    image: static_web:ouaarabe
    container_name: static_web
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: on-failure

volumes:
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: /tmp/wordpress
      type: none
      o: bind
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      device: /tmp/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

