version: '3.7'

  # nginx:
  #   build: srcs/requirements/nginx/
  #   image: nginx:ouaarabe
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - wp_vol:/var/www/html
  #   networks:
  #     - inception
  #   env_file:
  #     - .env
  #   restart: on-failure
  # wordpress:
  #   build: srcs/requirements/wordpress/
  #   image: wp:ouaarabe
  #   container_name: wp
  #   expose:
  #     - "9000"
  #   volumes:
  #     - wp_vol:/var/www/html
  #   # depends_on:
  #   #   - mariadb
  #   networks:
  #     - inception
  #   env_file:
  #     - .env
  #   restart: on-failure
services:
  mariadb:
    build: srcs/requirements/mariadb/
    image: mariadb:ouaarabe
    container_name: mariadb
    ports:
      - "3306"
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart : on-failure


volumes:
  # wp_vol:
  #   name: wordpress_vol
  #   driver: local
  #   driver_opts:
  #     device: /tmp/wordpress
  #     type: none
  #     o: bind
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      device: /tmp/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
    # driver: bridge

