version: '3.7'

services:
  nginx:
    build: nginx/
    image: nginx:ouaarabe
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  mariadb:
    build:
      context: requirements/mariadb/
      args:
        SQL_USER: ${SQL_USER}
        SQL_PASSWORD: ${SQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: mariadb:ouaarabe
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart : always


volumes:
  wp_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: /tmp/wordpress
      type: none
      o: bind
    maradb_vol:
      name: mariadb_vol
      driver_opts:
        device: /tmp/mariadb
        o: bind
        type: none

networks:
  inception:
    name: inception
    driver: bridge

